no api key version

diff --git a/grafana_dashboards/import_dashboards_apikey b/grafana_dashboards/import_dashboards_apikey
--- a/grafana_dashboards/import_dashboards_apikey
+++ b/grafana_dashboards/import_dashboards_apikey
@@ -3,15 +3,19 @@
 # add the "-x" option to the shebang line if you want a more verbose output
 #
 # 
-OPTSPEC=":hp:t:k:"
+
+#set -x 
+#set +x
+OPTSPEC=":hp:t:u:w:"
 
 show_help() {
 cat << EOF
-Usage: $0 [-p PATH] [-t TARGET_HOST] [-k API_KEY]
+Usage: $0 [-u Grafana_User] [-w Grafana_Password] [-p PATH] [-t TARGET_HOST]
 Script to import dashboards into Grafana
+    -u      Required. Grafana User
+    -w      Required. Grafana Password
     -p      Required. Root path containing JSON exports of the dashboards you want imported.
     -t      Required. The full URL of the target host
-    -k      Required. The API key to use on the target host
     
     -h      Display this help and exit.
 EOF
@@ -27,9 +31,11 @@ while getopts "$OPTSPEC" optchar; do
         p)
             DASH_DIR="$OPTARG";;
         t)
-            HOST="$OPTARG";;
-        k)
-            KEY="$OPTARG";;
+            TARGET_HOST="$OPTARG";;
+        u)
+            GRAFANA_USER="$OPTARG";;
+        w)
+            GRAFANA_PASSWORD="$OPTARG";;
         \?)
           echo "Invalid option: -$OPTARG" >&2
           exit 1
@@ -41,7 +47,7 @@ while getopts "$OPTSPEC" optchar; do
     esac
 done
 
-if [ -z "$DASH_DIR" ] || [ -z "$HOST" ] || [ -z "$KEY" ]; then
+if [ -z "$DASH_DIR" ] || [ -z "$TARGET_HOST" ] || [ -z "$GRAFANA_USER" ] || [ -z "$GRAFANA_PASSWORD" ]; then
     show_help
     exit 1
 fi
@@ -89,11 +95,33 @@ function log_title() {
    fi
 
    ${SETCOLOR_TITLE_PURPLE}
-   printf "|-------------------------------------------------------------------------|\n"
+   printf "|------------------------------------------------------------------------------------------------------------------------|\n"
    printf "|%s|\n" "$1";
-   printf "|-------------------------------------------------------------------------|\n"
+   printf "|------------------------------------------------------------------------------------------------------------------------|\n"
    ${SETCOLOR_NORMAL}
 }
+
+### API KEY GENERATION 
+
+KEYNAME=$(head -3 /dev/urandom | tr -cd '[:alnum:]' | cut -c -7)
+KEYLENGTH=70
+GENERATE_POST_DATA="{\"name\": \"${KEYNAME}\", \"role\": \"Admin\", \"secondsToLive\": 3600 }"
+
+if [ -n "$GRAFANA_USER" ] || [ -n "$GRAFANA_PASSWORD" ] || [ -n "$TARGET_HOST" ]; then
+    KEY=$(curl -X POST -H "Content-Type: application/json" -d "${GENERATE_POST_DATA}" "https://"${GRAFANA_USER}":"${GRAFANA_PASSWORD}"@"${TARGET_HOST}"/api/auth/keys" | jq -r '.key')
+    if [ ${#KEY} -ge $KEYLENGTH ]; then
+        log_title "---- API Key Generated successfully, correct character number generated in API Key, we're going into the next step -----"
+    else
+        log_title "------------------------------------------------- API Key is not valid ! ----------------------------------------------"
+        log_failure "$KEY does not contain the correct information to do API actions. Please Check, and try again."
+        exit 1
+        
+    fi
+else  
+    log_title "----------------- One of the parameters is not correct -----------------"
+    log_failure "Set correct parameters and try again."
+    exit 1
+fi
 
 if [ -d "$DASH_DIR" ]; then
     DASH_LIST=$(find "$DASH_DIR" -mindepth 1 -name \*.json)
@@ -103,7 +131,7 @@ if [ -d "$DASH_DIR" ]; then
         exit 1
     else
         FILESTOTAL=$(echo "$DASH_LIST" | wc -l)
-        log_title "----------------- Starting import of $FILESTOTAL dashboards -----------------"
+        log_title "------------------------------------------- Starting import of $FILESTOTAL dashboards -------------------------------------------"
     fi
 else
     log_title "----------------- $DASH_DIR directory not found! -----------------"
@@ -118,7 +146,7 @@ COUNTER=0
 for DASH_FILE in $DASH_LIST; do 
     COUNTER=$((COUNTER + 1))
     echo "Import $COUNTER/$FILESTOTAL: $DASH_FILE..."
-    RESULT=$(cat "$DASH_FILE" | jq '. * {overwrite: true, dashboard: {id: null}}' | curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $KEY" "$HOST"/api/dashboards/db -d @-)
+    RESULT=$(cat "$DASH_FILE" | jq '. * {overwrite: true, dashboard: {id: null}}' | curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $KEY" "https://$TARGET_HOST/api/dashboards/db" -d @-)
     if [[ "$RESULT" == *"success"* ]]; then
         log_success "$RESULT"
         NUMSUCCESS=$((NUMSUCCESS + 1))
@@ -128,5 +156,5 @@ for DASH_FILE in $DASH_LIST; do
     fi
 done
 
-log_title "Import complete. $NUMSUCCESS dashboards were successfully imported. $NUMFAILURE dashboard imports failed.";
-log_title "------------------------------ FINISHED ---------------------------------";
+log_title "------------ Import complete. $NUMSUCCESS dashboards were successfully imported. $NUMFAILURE dashboard imports failed.------------";
+log_title "-------------------------------------------------------- FINISHED ------------------------------------------------------";
